
waiting_quotes <- c("Unveiling the secrets of the universe... Please wait.",
                    "Einstein would be proud of our calculations... Just a moment, please.",
                    "Patience is the key to unlocking scientific wonders... Almost there!",
                    "Preparing the laboratory for groundbreaking experiments... Hold on tight!",
                    "In the realm of science, great things come to those who wait... Just a little longer.",
                    "The journey to knowledge begins with a single click... Loading.",
                    "Quantum entanglement in progress... Please be patient.",
                    "The scientific revolution awaits... Loading with anticipation.",
                    "Unraveling the mysteries of the cosmos... Just a few more seconds.",
                    "The quest for discovery demands time... Thank you for waiting.",
                    "Calculating the unknown variables of the universe... Almost ready.",
                    "Harnessing the power of science... Just a moment, please.",
                    "Diving deep into the ocean of knowledge... Loading your request.",
                    "Preparing the scientific wonders of tomorrow... Your patience is appreciated.",
                    "Unlocking the secrets of DNA... Please wait for the breakthrough.",
                    "The wheels of scientific progress are turning... Loading results.",
                    "Analyzing the data with meticulous precision... Almost done!",
                    "The gears of innovation are in motion... Thank you for your patience.",
                    "Exploring the frontiers of knowledge... Just a little more time.",
                    "The universe is vast, and so is the wait for scientific wonders... Loading.")